version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
  configuration:
    build: configuration/
    hostname: configuration
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.cloud.config.server.git.uri: /configuration
    volumes:
      - .:/configuration
    ports:
      - 8080:8080
  client:
    build: client/
    hostname: client
    environment:
      spring.rabbitmq.host: rabbitmq
    ports:
      - 8081:8080
    depends_on:
      - configuration